name: Ping Render Instance

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the deployed Render instance
        run: |
          echo "Pinging https://gupshup-skal.onrender.com..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://gupshup-skal.onrender.com)
          echo "HTTP Status: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "⚠️ Instance returned status $STATUS"
            exit 1
          fi
